#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

#Submit the reprocessed Data
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1 --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016B-23Sep2016-v3/MINIAOD SINGLEMUON2016B_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016C-23Sep2016-v1/MINIAOD SINGLEMUON2016C_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016D-23Sep2016-v1/MINIAOD SINGLEMUON2016D_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016E-23Sep2016-v1/MINIAOD SINGLEMUON2016E_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016F-23Sep2016-v1/MINIAOD SINGLEMUON2016F_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016G-23Sep2016-v1/MINIAOD SINGLEMUON2016G_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016H-PromptReco-v2/MINIAOD SINGLEMUON2016H_v2_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016H-PromptReco-v3/MINIAOD SINGLEMUON2016H_v3_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON.py  

#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016B-23Sep2016-v3/MINIAOD SINGLEELE2016B_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016C-23Sep2016-v1/MINIAOD SINGLEELE2016C_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016D-23Sep2016-v1/MINIAOD SINGLEELE2016D_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016E-23Sep2016-v1/MINIAOD SINGLEELE2016E_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016F-23Sep2016-v1/MINIAOD SINGLEELE2016F_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016G-23Sep2016-v1/MINIAOD SINGLEELE2016G_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
#/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016H-PromptReco-v2/MINIAOD SINGLEELE2016H_Boost_Nov28 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON.py  

/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016B-23Sep2016-v3/MINIAOD TAU2016B_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016C-23Sep2016-v1/MINIAOD TAU2016C_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016D-23Sep2016-v1/MINIAOD TAU2016D_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016E-23Sep2016-v1/MINIAOD TAU2016E_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016F-23Sep2016-v1/MINIAOD TAU2016F_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016G-23Sep2016-v1/MINIAOD TAU2016G_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON-ReReco.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016H-PromptReco-v2/MINIAOD TAU2016H_v2_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist   --vsize-limit=8000 --skip-existing-output   --input-files-per-job=1 --input-dbs-path=/Tau/Run2016H-PromptReco-v3/MINIAOD TAU2016H_v3_Boost_Nov29 $CMSSW_BASE $CMSSW_BASE/src/MonoHTauTau/CRAB/boosted/SUB-JSON.py  

